# Generated by Django 4.2.7 on 2026-02-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='岗位名称')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='公司名称')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('location', models.CharField(max_length=200, verbose_name='工作地点')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='最低薪资(k)')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='最高薪资(k)')),
                ('education_required', models.CharField(max_length=50, verbose_name='学历要求')),
                ('work_years_required', models.IntegerField(verbose_name='工作年限要求')),
                ('skills_required', models.TextField(help_text='用逗号分隔', verbose_name='技能要求')),
                ('job_description', models.TextField(verbose_name='岗位描述')),
                ('job_requirements', models.TextField(verbose_name='任职要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='发布HR')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
