# Generated by Django 4.2.7 on 2026-02-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待查看'), ('viewed', '已查看'), ('interested', '感兴趣'), ('interview', '邀请面试'), ('rejected', '不合适')], default='pending', max_length=20, verbose_name='状态')),
                ('hr_notes', models.TextField(blank=True, verbose_name='HR备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='查看时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='岗位')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='求职者')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '投递记录',
                'verbose_name_plural': '投递记录',
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'resume')},
            },
        ),
    ]
