# Generated by Django 4.2.7 on 2026-02-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='0-100分', verbose_name='匹配分数')),
                ('match_analysis', models.TextField(blank=True, verbose_name='匹配分析')),
                ('education_score', models.FloatField(default=0, verbose_name='学历匹配度')),
                ('experience_score', models.FloatField(default=0, verbose_name='经验匹配度')),
                ('skills_score', models.FloatField(default=0, verbose_name='技能匹配度')),
                ('interview_suggestions', models.TextField(blank=True, verbose_name='面试建议')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('interested', '感兴趣'), ('interview', '邀请面试'), ('rejected', '不合适')], default='pending', max_length=20, verbose_name='状态')),
                ('hr_notes', models.TextField(blank=True, verbose_name='HR备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.job', verbose_name='岗位')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '匹配结果',
                'verbose_name_plural': '匹配结果',
                'db_table': 'match_results',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('job', 'resume')},
            },
        ),
    ]
