# Generated by Django 4.2.7 on 2026-02-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_weight', models.FloatField(default=0.3, help_text='0-1之间', verbose_name='学历权重')),
                ('experience_weight', models.FloatField(default=0.4, help_text='0-1之间', verbose_name='经验权重')),
                ('skills_weight', models.FloatField(default=0.3, help_text='0-1之间', verbose_name='技能权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight_config', to='jobs.job', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '匹配权重配置',
                'verbose_name_plural': '匹配权重配置',
                'db_table': 'match_weight_configs',
            },
        ),
    ]
