# Generated by Django 4.2.7 on 2026-03-01 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_matchweightconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_resumes', models.IntegerField(default=0, verbose_name='简历总数')),
                ('matched_count', models.IntegerField(default=0, verbose_name='匹配数量')),
                ('avg_score', models.FloatField(default=0, verbose_name='平均分数')),
                ('excellent_count', models.IntegerField(default=0, verbose_name='优秀(80+)')),
                ('good_count', models.IntegerField(default=0, verbose_name='良好(60-80)')),
                ('fair_count', models.IntegerField(default=0, verbose_name='一般(40-60)')),
                ('poor_count', models.IntegerField(default=0, verbose_name='较差(<40)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='匹配时间')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='HR用户')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_sessions', to='jobs.job', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '匹配会话记录',
                'verbose_name_plural': '匹配会话记录',
                'db_table': 'matching_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
