# Generated by Django 4.2.7 on 2026-02-17 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='简历文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('status', models.CharField(choices=[('pending', '待解析'), ('parsed', '已解析'), ('failed', '解析失败')], default='pending', max_length=20, verbose_name='状态')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('education', models.CharField(blank=True, max_length=50, verbose_name='学历')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='毕业院校')),
                ('major', models.CharField(blank=True, max_length=200, verbose_name='专业')),
                ('work_years', models.IntegerField(blank=True, null=True, verbose_name='工作年限')),
                ('raw_text', models.TextField(blank=True, verbose_name='原始文本')),
                ('parsed_data', models.JSONField(blank=True, help_text='包含工作经历、项目经验、技能等', null=True, verbose_name='解析数据')),
                ('optimization_suggestions', models.TextField(blank=True, verbose_name='优化建议')),
                ('score', models.FloatField(default=0, help_text='AI评分，满分100', verbose_name='简历评分')),
                ('score_details', models.JSONField(blank=True, help_text='各维度评分', null=True, verbose_name='评分详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
